using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using UpdateControls;

namespace Strive.WPF.Model
{
    public class LogModel
    {
        private List<string> _logEntries = new List<string>();
        private int _maxEntries = 50;

        #region Independent properties
        // Generated by Update Controls --------------------------------
        private Independent _indMaxEntries = new Independent();
        private Independent _indLogEntries = new Independent();

        public void NewLogEntry(string logEntry)
        {
            _indLogEntries.OnSet();
            _logEntries.Insert(0, logEntry);
            while (_logEntries.Count > _maxEntries)
                _logEntries.RemoveAt(_maxEntries);
        }

        public IEnumerable<string> LogEntries
        {
            get { _indLogEntries.OnGet(); return _logEntries; }
        }

        public int MaxEntries
        {
            get { _indMaxEntries.OnGet(); return _maxEntries; }
            set { _indMaxEntries.OnSet(); _maxEntries = value; }
        }
        // End generated code --------------------------------
        #endregion
    }
}
