using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using UpdateControls;

namespace Strive.WPF.Model
{
    public class ServerStatusModel
    {
        private int _status = 0;
        private DateTime _started;

        #region Independent properties
        // Generated by Update Controls --------------------------------
        private Independent _indStatus = new Independent();
        private Independent _indStarted = new Independent();

        public int Status
        {
            get { _indStatus.OnGet(); return _status; }
            set { _indStatus.OnSet(); _status = value; }
        }

        public DateTime Started
        {
            get { _indStarted.OnGet(); return _started; }
            set { _indStarted.OnSet(); _started = value; }
        }
        // End generated code --------------------------------
        #endregion
    }
}