using System.Collections.Generic;
using UpdateControls;
using Strive.Model;


namespace Strive.Client.ViewModel
{
    public class WorldNavigation
    {
        // storing only the id, as the objects get replaced entirely
        private readonly HashSet<int> _selectedEntities = new HashSet<int>();
        private readonly HashSet<int> _selectedPlans = new HashSet<int>();
        private int? _mouseOverEntity;

        #region Independent properties
        // Generated by Update Controls --------------------------------
        private readonly Independent _indMouseOverEntity = new Independent();
        private readonly Independent _indSelectedEntities = new Independent();
        private readonly Independent _indSelectedPlans = new Independent();

        public void SetSelected(EntityModel e) { SetSelectedEntity(e.Id); }
        public void SetSelectedEntity(int id)
        {
            _indSelectedEntities.OnSet();
            _selectedEntities.Clear();
            _selectedEntities.Add(id);
        }

        public void AddSelected(EntityModel e) { AddSelectedEntity(e.Id); }
        public void AddSelectedEntity(int id)
        {
            _indSelectedEntities.OnSet();
            _selectedEntities.Add(id);
        }

        public void RemoveSelected(EntityModel e) { RemoveSelectedEntity(e.Id); }
        public void RemoveSelectedEntity(int id)
        {
            _indSelectedEntities.OnSet();
            _selectedEntities.Remove(id);
        }

        public bool IsSelected(EntityModel e) { return IsSelectedEntity(e.Id); }
        public bool IsSelectedEntity(int id)
        {
            _indSelectedEntities.OnGet();
            return _selectedEntities.Contains(id);
        }

        public IEnumerable<int> SelectedEntities
        {
            get { _indSelectedEntities.OnGet(); return _selectedEntities; }
        }

        public int? MouseOverEntity
        {
            get { _indMouseOverEntity.OnGet(); return _mouseOverEntity; }
            set { _indMouseOverEntity.OnSet(); _mouseOverEntity = value; }
        }

        public void SetSelected(PlanModel plan) { SetSelectedPlan(plan.Id); }
        public void SetSelectedPlan(int id)
        {
            _indSelectedPlans.OnSet();
            _selectedPlans.Clear();
            _selectedPlans.Add(id);
        }

        public void AddSelected(PlanModel plan) { AddSelectedPlan(plan.Id); }
        public void AddSelectedPlan(int id)
        {
            _indSelectedPlans.OnSet();
            _selectedPlans.Add(id);
        }

        public void RemoveSelected(PlanModel plan) { RemoveSelectedPlan(plan.Id); }
        public void RemoveSelectedPlan(int id)
        {
            _indSelectedPlans.OnSet();
            _selectedPlans.Remove(id);
        }

        public bool IsSelected(PlanModel plan) { return IsSelectedPlan(plan.Id); }
        public bool IsSelectedPlan(int id)
        {
            _indSelectedPlans.OnGet();
            return _selectedPlans.Contains(id);
        }

        public IEnumerable<int> SelectedPlans
        {
            get { _indSelectedPlans.OnGet(); return _selectedPlans; }
        }
        // End generated code --------------------------------
        #endregion
    }
}
