using System;
using System.Collections.Generic;
using System.Diagnostics.Contracts;
using UpdateControls;


namespace Strive.Client.Model
{
    public class DictionaryModel<TKeyType, TValueType>
    {
        private readonly Dictionary<TKeyType, TValueType> _entities = new Dictionary<TKeyType, TValueType>();

        public DictionaryModel(){}

        public DictionaryModel(IEnumerable<KeyValuePair<TKeyType, TValueType>> dictionary)
        {
            Contract.Requires<ArgumentNullException>(dictionary != null);

            foreach (var e in dictionary)
            {
                _entities[e.Key] = e.Value;
            }
        }

        #region Independent properties
        // Generated by Update Controls --------------------------------
        private readonly Independent _indEntities = new Independent();

        public void AddEntity(TKeyType id, TValueType entity)
        {
            _indEntities.OnSet();
            _entities[id] = entity;
        }

        public void DeleteEntity(TKeyType id)
        {
            _indEntities.OnSet();
            _entities.Remove(id);
        }

        public TValueType GetEntity(TKeyType id)
        {
            _indEntities.OnGet();
            return _entities[id];
        }

        public IEnumerable<TValueType> Entities
        {
            get { _indEntities.OnGet(); return _entities.Values; }
        }

        public Dictionary<TKeyType, TValueType> EntityDictionary
        {
            get { _indEntities.OnGet(); return _entities; }
        }

        public int Count
        {
            get { _indEntities.OnGet(); return _entities.Count; }
        }

        public void Clear()
        {
            _indEntities.OnSet();
            _entities.Clear();
        }

        public bool ContainsKey(TKeyType key)
        {
            _indEntities.OnGet();
            return _entities.ContainsKey(key);
        }

        public bool ContainsValue(TValueType value)
        {
            _indEntities.OnGet();
            return _entities.ContainsValue(value);
        }

        // End generated code --------------------------------
        #endregion
    }
}
