using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Text;

using UpdateControls;


namespace Strive.Client.Model
{
    public class EntityModel
    {
        public EntityModel(string name, string modelId, double x, double y, double z, double dirX, double dirY, double dirZ)
        {
            _name = name; _modelID = modelId; _x = x; _y = y; _z = z; _dirX = dirX; _dirY = dirY; _dirZ = dirZ;
        }

        private string _name;
        private string _modelID;
        private double _x;
        private double _y;
        private double _z;
        private double _dirX;
        private double _dirY;
        private double _dirZ;

        #region Independent properties
        // Generated by Update Controls --------------------------------
        private Independent _indName = new Independent();
        private Independent _indModelID = new Independent();
        private Independent _indX = new Independent();
        private Independent _indY = new Independent();
        private Independent _indZ = new Independent();
        private Independent _indDirX = new Independent();
        private Independent _indDirY = new Independent();
        private Independent _indDirZ = new Independent();

        public string Name
        {
            get { _indName.OnGet(); return _name; }
            set { _indName.OnSet(); _name = value; }
        }

        public string ModelID
        {
            get { _indModelID.OnGet(); return _modelID; }
            set { _indModelID.OnSet(); _modelID = value; }
        }

        public double X
        {
            get { _indX.OnGet(); return _x; }
            set { _indX.OnSet(); _x = value; }
        }

        public double Y
        {
            get { _indY.OnGet(); return _y; }
            set { _indY.OnSet(); _y = value; }
        }

        public double Z
        {
            get { _indZ.OnGet(); return _z; }
            set { _indZ.OnSet(); _z = value; }
        }

        public double DirX
        {
            get { _indDirX.OnGet(); return _dirX; }
            set { _indDirX.OnSet(); _dirX = value; }
        }

        public double DirY
        {
            get { _indDirY.OnGet(); return _dirY; }
            set { _indDirY.OnSet(); _dirY = value; }
        }

        public double DirZ
        {
            get { _indDirZ.OnGet(); return _dirZ; }
            set { _indDirZ.OnSet(); _dirZ = value; }
        }
        // End generated code --------------------------------
        #endregion
    }
}
