using System.Windows.Media.Media3D;

using UpdateControls;


namespace Strive.Client.Model
{
    public class EntityModel
    {
        public EntityModel(string name, string modelId, Vector3D position, Quaternion rotation)
        {
            _name = name;
            _modelId = modelId;
            _position = position;
            _rotation = rotation;
        }

        private string _name;
        private string _modelId;
        private Vector3D _position;
        private Quaternion _rotation;

        #region Independent properties
        // Generated by Update Controls --------------------------------
        private Independent _indName = new Independent();
        private Independent _indModelID = new Independent();
        private Independent _indPosition = new Independent();
        private Independent _indRotation = new Independent();

        public string Name
        {
            get { _indName.OnGet(); return _name; }
            set { _indName.OnSet(); _name = value; }
        }

        public string ModelId
        {
            get { _indModelID.OnGet(); return _modelId; }
            set { _indModelID.OnSet(); _modelId = value; }
        }

        public Vector3D Position
        {
            get { _indPosition.OnGet(); return _position; }
            set { _indPosition.OnSet(); _position = value; }
        }

        public Quaternion Rotation
        {
            get { _indRotation.OnGet(); return _rotation; }
            set { _indRotation.OnSet(); _rotation = value; }
        }
        // End generated code --------------------------------
        #endregion
    }
}
