// <copyright file="EntityViewModelTest.ToString01.g.cs">Copyright ©  2010</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Strive.Client.Model;
using System.Windows.Media.Media3D;
using Microsoft.Pex.Framework;
using NUnit.Framework;
using Microsoft.Pex.Framework.Generated;

namespace Strive.Client.ViewModel
{
    public partial class EntityViewModelTest
    {
[Test]
[PexGeneratedBy(typeof(EntityViewModelTest))]
public void ToString01137()
{
    EntityModel entityModel;
    WorldNavigation worldNavigation;
    EntityViewModel entityViewModel;
    string s;
    entityModel =
      new EntityModel("\0", "\0", default(Vector3D), default(Quaternion));
    worldNavigation = new WorldNavigation();
    worldNavigation.MouseOverEntity = (EntityModel)null;
    entityViewModel = new EntityViewModel(entityModel, worldNavigation);
    s = this.ToString01(entityViewModel);
    PexAssert.AreEqual<string>("\0", s);
    PexAssert.IsNotNull((object)entityViewModel);
    PexAssert.IsNotNull(entityViewModel.Entity);
}
    }
}
