using System;

namespace www.strive3d.net.Game
{

	// This code is generated by a tool
		
	public class CommandFactory
	{

		#region Permanent
		private System.Collections.Hashtable _commands = new System.Collections.Hashtable();
		private System.Data.SqlClient.SqlConnection _connection;
			

		public System.Data.SqlClient.SqlConnection Connection
		{
			get
			{
				return _connection;
			}
		}

		public CommandFactory()
		{
			_connection = new System.Data.SqlClient.SqlConnection(System.Configuration.ConfigurationSettings.AppSettings["ConnectionString"].ToString());
			_connection.Open();
		}

		/// 
		/// Initialises the CommandFactory with a SqlConnection.ConnectionString compatible string
		/// 
		/// The SqlConnection.ConnectionString to use
		/// Ths CommandFactory will create a new SqlConnection and Open it
		public CommandFactory(string connectionString)
		{
			_connection = new System.Data.SqlClient.SqlConnection(connectionString);
			_connection.Open();
		}

		/// 
		/// Initialises the CommandFactory with a SqlConnection object
		/// 
		/// The SqlConnection object this CommandFactory should use
		/// The CommandFactory assumes this is an open, valid SqlConnection
		public CommandFactory(System.Data.SqlClient.SqlConnection connection)
		{
			_connection = connection;

		}

		/// 
		/// Finalisers the associated Connection when the CommandFactory is finalised
		/// 
		~CommandFactory()
		{
			this.Close();
		}

		public void Close()
		{
			if(_connection.State != System.Data.ConnectionState.Closed)
			{
				_connection.Close();
			}
		}
			
		private bool isCommandCached(string commandID)
		{
			return _commands.Contains(commandID);
		}

		public System.Data.SqlClient.SqlCommand GetSqlCommand(string sql)
		{
			string thisID = sql;
			System.Data.SqlClient.SqlCommand thisCommand;
			if(!this.isCommandCached(thisID))
			{
				thisCommand = new System.Data.SqlClient.SqlCommand();
	
				thisCommand.Connection = _connection;
				thisCommand.CommandType = System.Data.CommandType.Text;
				thisCommand.CommandText = sql;

				thisCommand.Prepare();
			}
			else
			{
				thisCommand = (System.Data.SqlClient.SqlCommand)this._commands[thisID];
			}

			return thisCommand;
		}
		
		#endregion

		
		public System.Data.SqlClient.SqlCommand ActivatePlayer(System.Data.SqlTypes.SqlGuid PlayerKey)
		{
			const string thisID = "1774629365";
			System.Data.SqlClient.SqlCommand thisCommand;
			if(!this.isCommandCached(thisID))
			{
				// create and add to cache
				thisCommand = new System.Data.SqlClient.SqlCommand();

				thisCommand.Connection = _connection;
				thisCommand.CommandType = System.Data.CommandType.StoredProcedure;
				thisCommand.CommandText = "ActivatePlayer";
					
				// Parameters:
					
				System.Data.SqlClient.SqlParameter param;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@PlayerKey";
				param.SourceColumn = "PlayerKey";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		

				// not sure of the usefullness of this
				// i never really got prepared statements
				thisCommand.Prepare();					
					
				_commands.Add(thisID, thisCommand);
			}
			else
			{
				thisCommand = (System.Data.SqlClient.SqlCommand)this._commands[thisID];
			}
				
				
			thisCommand.Parameters["@PlayerKey"].Value = PlayerKey;
		
								
			return thisCommand;
			
		}
	
			
		public System.Data.SqlClient.SqlCommand ActivatePlayer()
		{
			const string thisID = "1774629365";
			System.Data.SqlClient.SqlCommand thisCommand;
			if(!this.isCommandCached(thisID))
			{
				// create and add to cache
				thisCommand = new System.Data.SqlClient.SqlCommand();

				thisCommand.Connection = _connection;
				thisCommand.CommandType = System.Data.CommandType.StoredProcedure;
				thisCommand.CommandText = "ActivatePlayer";
					
				// Parameters:
					
				System.Data.SqlClient.SqlParameter param;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@PlayerKey";
				param.SourceColumn = "PlayerKey";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
							
					
				// not sure of the usefullness of this
				// i never really got prepared statements
				thisCommand.Prepare();					
					
				_commands.Add(thisID, thisCommand);
			}
			else
			{
				thisCommand = (System.Data.SqlClient.SqlCommand)this._commands[thisID];
			}

			return thisCommand;
			
		}
	
			
		public System.Data.SqlClient.SqlCommand AreaSquareDetails(System.Data.SqlTypes.SqlInt32 AbstractionSize, System.Data.SqlTypes.SqlInt32 Offset)
		{
			const string thisID = "1950629992";
			System.Data.SqlClient.SqlCommand thisCommand;
			if(!this.isCommandCached(thisID))
			{
				// create and add to cache
				thisCommand = new System.Data.SqlClient.SqlCommand();

				thisCommand.Connection = _connection;
				thisCommand.CommandType = System.Data.CommandType.StoredProcedure;
				thisCommand.CommandText = "AreaSquareDetails";
					
				// Parameters:
					
				System.Data.SqlClient.SqlParameter param;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@AbstractionSize";
				param.SourceColumn = "AbstractionSize";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@Offset";
				param.SourceColumn = "Offset";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		

				// not sure of the usefullness of this
				// i never really got prepared statements
				thisCommand.Prepare();					
					
				_commands.Add(thisID, thisCommand);
			}
			else
			{
				thisCommand = (System.Data.SqlClient.SqlCommand)this._commands[thisID];
			}
				
				
			thisCommand.Parameters["@AbstractionSize"].Value = AbstractionSize;
		
			thisCommand.Parameters["@Offset"].Value = Offset;
		
								
			return thisCommand;
			
		}
	
			
		public System.Data.SqlClient.SqlCommand AreaSquareDetails()
		{
			const string thisID = "1950629992";
			System.Data.SqlClient.SqlCommand thisCommand;
			if(!this.isCommandCached(thisID))
			{
				// create and add to cache
				thisCommand = new System.Data.SqlClient.SqlCommand();

				thisCommand.Connection = _connection;
				thisCommand.CommandType = System.Data.CommandType.StoredProcedure;
				thisCommand.CommandText = "AreaSquareDetails";
					
				// Parameters:
					
				System.Data.SqlClient.SqlParameter param;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@AbstractionSize";
				param.SourceColumn = "AbstractionSize";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@Offset";
				param.SourceColumn = "Offset";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
							
					
				// not sure of the usefullness of this
				// i never really got prepared statements
				thisCommand.Prepare();					
					
				_commands.Add(thisID, thisCommand);
			}
			else
			{
				thisCommand = (System.Data.SqlClient.SqlCommand)this._commands[thisID];
			}

			return thisCommand;
			
		}
	
			
		public System.Data.SqlClient.SqlCommand CreateCharacter(System.Data.SqlTypes.SqlString ObjectTemplateName, System.Data.SqlTypes.SqlInt32 ModelID, System.Data.SqlTypes.SqlInt32 PlayerID, System.Data.SqlTypes.SqlInt32 EnumRaceID)
		{
			const string thisID = "155147598";
			System.Data.SqlClient.SqlCommand thisCommand;
			if(!this.isCommandCached(thisID))
			{
				// create and add to cache
				thisCommand = new System.Data.SqlClient.SqlCommand();

				thisCommand.Connection = _connection;
				thisCommand.CommandType = System.Data.CommandType.StoredProcedure;
				thisCommand.CommandText = "CreateCharacter";
					
				// Parameters:
					
				System.Data.SqlClient.SqlParameter param;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@ObjectTemplateName";
				param.SourceColumn = "ObjectTemplateName";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@ModelID";
				param.SourceColumn = "ModelID";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@PlayerID";
				param.SourceColumn = "PlayerID";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@EnumRaceID";
				param.SourceColumn = "EnumRaceID";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		

				// not sure of the usefullness of this
				// i never really got prepared statements
				thisCommand.Prepare();					
					
				_commands.Add(thisID, thisCommand);
			}
			else
			{
				thisCommand = (System.Data.SqlClient.SqlCommand)this._commands[thisID];
			}
				
				
			thisCommand.Parameters["@ObjectTemplateName"].Value = ObjectTemplateName;
		
			thisCommand.Parameters["@ModelID"].Value = ModelID;
		
			thisCommand.Parameters["@PlayerID"].Value = PlayerID;
		
			thisCommand.Parameters["@EnumRaceID"].Value = EnumRaceID;
		
								
			return thisCommand;
			
		}
	
			
		public System.Data.SqlClient.SqlCommand CreateCharacter()
		{
			const string thisID = "155147598";
			System.Data.SqlClient.SqlCommand thisCommand;
			if(!this.isCommandCached(thisID))
			{
				// create and add to cache
				thisCommand = new System.Data.SqlClient.SqlCommand();

				thisCommand.Connection = _connection;
				thisCommand.CommandType = System.Data.CommandType.StoredProcedure;
				thisCommand.CommandText = "CreateCharacter";
					
				// Parameters:
					
				System.Data.SqlClient.SqlParameter param;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@ObjectTemplateName";
				param.SourceColumn = "ObjectTemplateName";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@ModelID";
				param.SourceColumn = "ModelID";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@PlayerID";
				param.SourceColumn = "PlayerID";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@EnumRaceID";
				param.SourceColumn = "EnumRaceID";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
							
					
				// not sure of the usefullness of this
				// i never really got prepared statements
				thisCommand.Prepare();					
					
				_commands.Add(thisID, thisCommand);
			}
			else
			{
				thisCommand = (System.Data.SqlClient.SqlCommand)this._commands[thisID];
			}

			return thisCommand;
			
		}
	
			
		public System.Data.SqlClient.SqlCommand CreateGroupsTable(System.Data.SqlTypes.SqlInt32 AbstractionSize, System.Data.SqlTypes.SqlBoolean AutomaticOffset, System.Data.SqlTypes.SqlInt32 LargestCoordX, System.Data.SqlTypes.SqlInt32 SmallestCoordX, System.Data.SqlTypes.SqlInt32 LargestCoordZ, System.Data.SqlTypes.SqlInt32 SmallestCoordZ)
		{
			const string thisID = "1934629935";
			System.Data.SqlClient.SqlCommand thisCommand;
			if(!this.isCommandCached(thisID))
			{
				// create and add to cache
				thisCommand = new System.Data.SqlClient.SqlCommand();

				thisCommand.Connection = _connection;
				thisCommand.CommandType = System.Data.CommandType.StoredProcedure;
				thisCommand.CommandText = "CreateGroupsTable";
					
				// Parameters:
					
				System.Data.SqlClient.SqlParameter param;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@AbstractionSize";
				param.SourceColumn = "AbstractionSize";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@AutomaticOffset";
				param.SourceColumn = "AutomaticOffset";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@LargestCoordX";
				param.SourceColumn = "LargestCoordX";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@SmallestCoordX";
				param.SourceColumn = "SmallestCoordX";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@LargestCoordZ";
				param.SourceColumn = "LargestCoordZ";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@SmallestCoordZ";
				param.SourceColumn = "SmallestCoordZ";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		

				// not sure of the usefullness of this
				// i never really got prepared statements
				thisCommand.Prepare();					
					
				_commands.Add(thisID, thisCommand);
			}
			else
			{
				thisCommand = (System.Data.SqlClient.SqlCommand)this._commands[thisID];
			}
				
				
			thisCommand.Parameters["@AbstractionSize"].Value = AbstractionSize;
		
			thisCommand.Parameters["@AutomaticOffset"].Value = AutomaticOffset;
		
			thisCommand.Parameters["@LargestCoordX"].Value = LargestCoordX;
		
			thisCommand.Parameters["@SmallestCoordX"].Value = SmallestCoordX;
		
			thisCommand.Parameters["@LargestCoordZ"].Value = LargestCoordZ;
		
			thisCommand.Parameters["@SmallestCoordZ"].Value = SmallestCoordZ;
		
								
			return thisCommand;
			
		}
	
			
		public System.Data.SqlClient.SqlCommand CreateGroupsTable()
		{
			const string thisID = "1934629935";
			System.Data.SqlClient.SqlCommand thisCommand;
			if(!this.isCommandCached(thisID))
			{
				// create and add to cache
				thisCommand = new System.Data.SqlClient.SqlCommand();

				thisCommand.Connection = _connection;
				thisCommand.CommandType = System.Data.CommandType.StoredProcedure;
				thisCommand.CommandText = "CreateGroupsTable";
					
				// Parameters:
					
				System.Data.SqlClient.SqlParameter param;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@AbstractionSize";
				param.SourceColumn = "AbstractionSize";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@AutomaticOffset";
				param.SourceColumn = "AutomaticOffset";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@LargestCoordX";
				param.SourceColumn = "LargestCoordX";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@SmallestCoordX";
				param.SourceColumn = "SmallestCoordX";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@LargestCoordZ";
				param.SourceColumn = "LargestCoordZ";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@SmallestCoordZ";
				param.SourceColumn = "SmallestCoordZ";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
							
					
				// not sure of the usefullness of this
				// i never really got prepared statements
				thisCommand.Prepare();					
					
				_commands.Add(thisID, thisCommand);
			}
			else
			{
				thisCommand = (System.Data.SqlClient.SqlCommand)this._commands[thisID];
			}

			return thisCommand;
			
		}
	
			
		public System.Data.SqlClient.SqlCommand CreateMirror(System.Data.SqlTypes.SqlInt32 ObjectTemplateID, System.Data.SqlTypes.SqlInt32 X, System.Data.SqlTypes.SqlInt32 Y, System.Data.SqlTypes.SqlInt32 Z, System.Data.SqlTypes.SqlInt32 HeadingX, System.Data.SqlTypes.SqlInt32 HeadingY, System.Data.SqlTypes.SqlInt32 HeadingZ)
		{
			const string thisID = "1854629650";
			System.Data.SqlClient.SqlCommand thisCommand;
			if(!this.isCommandCached(thisID))
			{
				// create and add to cache
				thisCommand = new System.Data.SqlClient.SqlCommand();

				thisCommand.Connection = _connection;
				thisCommand.CommandType = System.Data.CommandType.StoredProcedure;
				thisCommand.CommandText = "CreateMirror";
					
				// Parameters:
					
				System.Data.SqlClient.SqlParameter param;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@ObjectTemplateID";
				param.SourceColumn = "ObjectTemplateID";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@X";
				param.SourceColumn = "X";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@Y";
				param.SourceColumn = "Y";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@Z";
				param.SourceColumn = "Z";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@HeadingX";
				param.SourceColumn = "HeadingX";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@HeadingY";
				param.SourceColumn = "HeadingY";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@HeadingZ";
				param.SourceColumn = "HeadingZ";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		

				// not sure of the usefullness of this
				// i never really got prepared statements
				thisCommand.Prepare();					
					
				_commands.Add(thisID, thisCommand);
			}
			else
			{
				thisCommand = (System.Data.SqlClient.SqlCommand)this._commands[thisID];
			}
				
				
			thisCommand.Parameters["@ObjectTemplateID"].Value = ObjectTemplateID;
		
			thisCommand.Parameters["@X"].Value = X;
		
			thisCommand.Parameters["@Y"].Value = Y;
		
			thisCommand.Parameters["@Z"].Value = Z;
		
			thisCommand.Parameters["@HeadingX"].Value = HeadingX;
		
			thisCommand.Parameters["@HeadingY"].Value = HeadingY;
		
			thisCommand.Parameters["@HeadingZ"].Value = HeadingZ;
		
								
			return thisCommand;
			
		}
	
			
		public System.Data.SqlClient.SqlCommand CreateMirror()
		{
			const string thisID = "1854629650";
			System.Data.SqlClient.SqlCommand thisCommand;
			if(!this.isCommandCached(thisID))
			{
				// create and add to cache
				thisCommand = new System.Data.SqlClient.SqlCommand();

				thisCommand.Connection = _connection;
				thisCommand.CommandType = System.Data.CommandType.StoredProcedure;
				thisCommand.CommandText = "CreateMirror";
					
				// Parameters:
					
				System.Data.SqlClient.SqlParameter param;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@ObjectTemplateID";
				param.SourceColumn = "ObjectTemplateID";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@X";
				param.SourceColumn = "X";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@Y";
				param.SourceColumn = "Y";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@Z";
				param.SourceColumn = "Z";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@HeadingX";
				param.SourceColumn = "HeadingX";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@HeadingY";
				param.SourceColumn = "HeadingY";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@HeadingZ";
				param.SourceColumn = "HeadingZ";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
							
					
				// not sure of the usefullness of this
				// i never really got prepared statements
				thisCommand.Prepare();					
					
				_commands.Add(thisID, thisCommand);
			}
			else
			{
				thisCommand = (System.Data.SqlClient.SqlCommand)this._commands[thisID];
			}

			return thisCommand;
			
		}
	
			
		public System.Data.SqlClient.SqlCommand CreateMobile(System.Data.SqlTypes.SqlInt32 AreaID, System.Data.SqlTypes.SqlString ObjectTemplateName, System.Data.SqlTypes.SqlInt32 ModelID, System.Data.SqlTypes.SqlInt32 PlayerID, System.Data.SqlTypes.SqlInt32 EnumRaceID, System.Data.SqlTypes.SqlInt32 Level, System.Data.SqlTypes.SqlInt32 Strength, System.Data.SqlTypes.SqlInt32 Constitution, System.Data.SqlTypes.SqlInt32 Cognition, System.Data.SqlTypes.SqlInt32 Willpower, System.Data.SqlTypes.SqlInt32 Dexterity, System.Data.SqlTypes.SqlInt32 Hitpoints, System.Data.SqlTypes.SqlInt32 GoldCarried, System.Data.SqlTypes.SqlInt32 GoldBanked, System.Data.SqlTypes.SqlInt32 EnumSexID, System.Data.SqlTypes.SqlInt32 EnumMobileSizeID, System.Data.SqlTypes.SqlInt32 EnumMobileStateID, System.Data.SqlTypes.SqlInt32 X, System.Data.SqlTypes.SqlInt32 Y, System.Data.SqlTypes.SqlInt32 Z, System.Data.SqlTypes.SqlInt32 HeadingX, System.Data.SqlTypes.SqlInt32 HeadingY, System.Data.SqlTypes.SqlInt32 HeadingZ)
		{
			const string thisID = "1870629707";
			System.Data.SqlClient.SqlCommand thisCommand;
			if(!this.isCommandCached(thisID))
			{
				// create and add to cache
				thisCommand = new System.Data.SqlClient.SqlCommand();

				thisCommand.Connection = _connection;
				thisCommand.CommandType = System.Data.CommandType.StoredProcedure;
				thisCommand.CommandText = "CreateMobile";
					
				// Parameters:
					
				System.Data.SqlClient.SqlParameter param;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@AreaID";
				param.SourceColumn = "AreaID";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@ObjectTemplateName";
				param.SourceColumn = "ObjectTemplateName";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@ModelID";
				param.SourceColumn = "ModelID";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@PlayerID";
				param.SourceColumn = "PlayerID";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@EnumRaceID";
				param.SourceColumn = "EnumRaceID";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@Level";
				param.SourceColumn = "Level";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@Strength";
				param.SourceColumn = "Strength";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@Constitution";
				param.SourceColumn = "Constitution";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@Cognition";
				param.SourceColumn = "Cognition";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@Willpower";
				param.SourceColumn = "Willpower";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@Dexterity";
				param.SourceColumn = "Dexterity";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@Hitpoints";
				param.SourceColumn = "Hitpoints";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@GoldCarried";
				param.SourceColumn = "GoldCarried";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@GoldBanked";
				param.SourceColumn = "GoldBanked";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@EnumSexID";
				param.SourceColumn = "EnumSexID";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@EnumMobileSizeID";
				param.SourceColumn = "EnumMobileSizeID";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@EnumMobileStateID";
				param.SourceColumn = "EnumMobileStateID";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@X";
				param.SourceColumn = "X";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@Y";
				param.SourceColumn = "Y";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@Z";
				param.SourceColumn = "Z";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@HeadingX";
				param.SourceColumn = "HeadingX";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@HeadingY";
				param.SourceColumn = "HeadingY";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@HeadingZ";
				param.SourceColumn = "HeadingZ";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		

				// not sure of the usefullness of this
				// i never really got prepared statements
				thisCommand.Prepare();					
					
				_commands.Add(thisID, thisCommand);
			}
			else
			{
				thisCommand = (System.Data.SqlClient.SqlCommand)this._commands[thisID];
			}
				
				
			thisCommand.Parameters["@AreaID"].Value = AreaID;
		
			thisCommand.Parameters["@ObjectTemplateName"].Value = ObjectTemplateName;
		
			thisCommand.Parameters["@ModelID"].Value = ModelID;
		
			thisCommand.Parameters["@PlayerID"].Value = PlayerID;
		
			thisCommand.Parameters["@EnumRaceID"].Value = EnumRaceID;
		
			thisCommand.Parameters["@Level"].Value = Level;
		
			thisCommand.Parameters["@Strength"].Value = Strength;
		
			thisCommand.Parameters["@Constitution"].Value = Constitution;
		
			thisCommand.Parameters["@Cognition"].Value = Cognition;
		
			thisCommand.Parameters["@Willpower"].Value = Willpower;
		
			thisCommand.Parameters["@Dexterity"].Value = Dexterity;
		
			thisCommand.Parameters["@Hitpoints"].Value = Hitpoints;
		
			thisCommand.Parameters["@GoldCarried"].Value = GoldCarried;
		
			thisCommand.Parameters["@GoldBanked"].Value = GoldBanked;
		
			thisCommand.Parameters["@EnumSexID"].Value = EnumSexID;
		
			thisCommand.Parameters["@EnumMobileSizeID"].Value = EnumMobileSizeID;
		
			thisCommand.Parameters["@EnumMobileStateID"].Value = EnumMobileStateID;
		
			thisCommand.Parameters["@X"].Value = X;
		
			thisCommand.Parameters["@Y"].Value = Y;
		
			thisCommand.Parameters["@Z"].Value = Z;
		
			thisCommand.Parameters["@HeadingX"].Value = HeadingX;
		
			thisCommand.Parameters["@HeadingY"].Value = HeadingY;
		
			thisCommand.Parameters["@HeadingZ"].Value = HeadingZ;
		
								
			return thisCommand;
			
		}
	
			
		public System.Data.SqlClient.SqlCommand CreateMobile()
		{
			const string thisID = "1870629707";
			System.Data.SqlClient.SqlCommand thisCommand;
			if(!this.isCommandCached(thisID))
			{
				// create and add to cache
				thisCommand = new System.Data.SqlClient.SqlCommand();

				thisCommand.Connection = _connection;
				thisCommand.CommandType = System.Data.CommandType.StoredProcedure;
				thisCommand.CommandText = "CreateMobile";
					
				// Parameters:
					
				System.Data.SqlClient.SqlParameter param;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@AreaID";
				param.SourceColumn = "AreaID";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@ObjectTemplateName";
				param.SourceColumn = "ObjectTemplateName";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@ModelID";
				param.SourceColumn = "ModelID";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@PlayerID";
				param.SourceColumn = "PlayerID";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@EnumRaceID";
				param.SourceColumn = "EnumRaceID";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@Level";
				param.SourceColumn = "Level";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@Strength";
				param.SourceColumn = "Strength";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@Constitution";
				param.SourceColumn = "Constitution";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@Cognition";
				param.SourceColumn = "Cognition";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@Willpower";
				param.SourceColumn = "Willpower";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@Dexterity";
				param.SourceColumn = "Dexterity";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@Hitpoints";
				param.SourceColumn = "Hitpoints";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@GoldCarried";
				param.SourceColumn = "GoldCarried";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@GoldBanked";
				param.SourceColumn = "GoldBanked";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@EnumSexID";
				param.SourceColumn = "EnumSexID";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@EnumMobileSizeID";
				param.SourceColumn = "EnumMobileSizeID";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@EnumMobileStateID";
				param.SourceColumn = "EnumMobileStateID";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@X";
				param.SourceColumn = "X";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@Y";
				param.SourceColumn = "Y";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@Z";
				param.SourceColumn = "Z";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@HeadingX";
				param.SourceColumn = "HeadingX";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@HeadingY";
				param.SourceColumn = "HeadingY";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@HeadingZ";
				param.SourceColumn = "HeadingZ";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
							
					
				// not sure of the usefullness of this
				// i never really got prepared statements
				thisCommand.Prepare();					
					
				_commands.Add(thisID, thisCommand);
			}
			else
			{
				thisCommand = (System.Data.SqlClient.SqlCommand)this._commands[thisID];
			}

			return thisCommand;
			
		}
	
			
		public System.Data.SqlClient.SqlCommand CreateModel(System.Data.SqlTypes.SqlString ModelName, System.Data.SqlTypes.SqlInt32 PlayerID, System.Data.SqlTypes.SqlString ModelDescription)
		{
			const string thisID = "2046630334";
			System.Data.SqlClient.SqlCommand thisCommand;
			if(!this.isCommandCached(thisID))
			{
				// create and add to cache
				thisCommand = new System.Data.SqlClient.SqlCommand();

				thisCommand.Connection = _connection;
				thisCommand.CommandType = System.Data.CommandType.StoredProcedure;
				thisCommand.CommandText = "CreateModel";
					
				// Parameters:
					
				System.Data.SqlClient.SqlParameter param;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@ModelName";
				param.SourceColumn = "ModelName";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@PlayerID";
				param.SourceColumn = "PlayerID";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@ModelDescription";
				param.SourceColumn = "ModelDescription";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		

				// not sure of the usefullness of this
				// i never really got prepared statements
				thisCommand.Prepare();					
					
				_commands.Add(thisID, thisCommand);
			}
			else
			{
				thisCommand = (System.Data.SqlClient.SqlCommand)this._commands[thisID];
			}
				
				
			thisCommand.Parameters["@ModelName"].Value = ModelName;
		
			thisCommand.Parameters["@PlayerID"].Value = PlayerID;
		
			thisCommand.Parameters["@ModelDescription"].Value = ModelDescription;
		
								
			return thisCommand;
			
		}
	
			
		public System.Data.SqlClient.SqlCommand CreateModel()
		{
			const string thisID = "2046630334";
			System.Data.SqlClient.SqlCommand thisCommand;
			if(!this.isCommandCached(thisID))
			{
				// create and add to cache
				thisCommand = new System.Data.SqlClient.SqlCommand();

				thisCommand.Connection = _connection;
				thisCommand.CommandType = System.Data.CommandType.StoredProcedure;
				thisCommand.CommandText = "CreateModel";
					
				// Parameters:
					
				System.Data.SqlClient.SqlParameter param;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@ModelName";
				param.SourceColumn = "ModelName";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@PlayerID";
				param.SourceColumn = "PlayerID";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@ModelDescription";
				param.SourceColumn = "ModelDescription";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
							
					
				// not sure of the usefullness of this
				// i never really got prepared statements
				thisCommand.Prepare();					
					
				_commands.Add(thisID, thisCommand);
			}
			else
			{
				thisCommand = (System.Data.SqlClient.SqlCommand)this._commands[thisID];
			}

			return thisCommand;
			
		}
	
			
		public System.Data.SqlClient.SqlCommand CreatePlayer(System.Data.SqlTypes.SqlString PlayerEmail, System.Data.SqlTypes.SqlString PlayerPassword)
		{
			const string thisID = "1790629422";
			System.Data.SqlClient.SqlCommand thisCommand;
			if(!this.isCommandCached(thisID))
			{
				// create and add to cache
				thisCommand = new System.Data.SqlClient.SqlCommand();

				thisCommand.Connection = _connection;
				thisCommand.CommandType = System.Data.CommandType.StoredProcedure;
				thisCommand.CommandText = "CreatePlayer";
					
				// Parameters:
					
				System.Data.SqlClient.SqlParameter param;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@PlayerEmail";
				param.SourceColumn = "PlayerEmail";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@PlayerPassword";
				param.SourceColumn = "PlayerPassword";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		

				// not sure of the usefullness of this
				// i never really got prepared statements
				thisCommand.Prepare();					
					
				_commands.Add(thisID, thisCommand);
			}
			else
			{
				thisCommand = (System.Data.SqlClient.SqlCommand)this._commands[thisID];
			}
				
				
			thisCommand.Parameters["@PlayerEmail"].Value = PlayerEmail;
		
			thisCommand.Parameters["@PlayerPassword"].Value = PlayerPassword;
		
								
			return thisCommand;
			
		}
	
			
		public System.Data.SqlClient.SqlCommand CreatePlayer()
		{
			const string thisID = "1790629422";
			System.Data.SqlClient.SqlCommand thisCommand;
			if(!this.isCommandCached(thisID))
			{
				// create and add to cache
				thisCommand = new System.Data.SqlClient.SqlCommand();

				thisCommand.Connection = _connection;
				thisCommand.CommandType = System.Data.CommandType.StoredProcedure;
				thisCommand.CommandText = "CreatePlayer";
					
				// Parameters:
					
				System.Data.SqlClient.SqlParameter param;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@PlayerEmail";
				param.SourceColumn = "PlayerEmail";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@PlayerPassword";
				param.SourceColumn = "PlayerPassword";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
							
					
				// not sure of the usefullness of this
				// i never really got prepared statements
				thisCommand.Prepare();					
					
				_commands.Add(thisID, thisCommand);
			}
			else
			{
				thisCommand = (System.Data.SqlClient.SqlCommand)this._commands[thisID];
			}

			return thisCommand;
			
		}
	
			
		public System.Data.SqlClient.SqlCommand CreateTerrain(System.Data.SqlTypes.SqlInt32 AreaID, System.Data.SqlTypes.SqlString ObjectTemplateName, System.Data.SqlTypes.SqlInt32 ModelID, System.Data.SqlTypes.SqlInt32 PlayerID, System.Data.SqlTypes.SqlInt32 EnumTerrainTypeID, System.Data.SqlTypes.SqlInt32 X, System.Data.SqlTypes.SqlInt32 Y, System.Data.SqlTypes.SqlInt32 Z, System.Data.SqlTypes.SqlInt32 HeadingX, System.Data.SqlTypes.SqlInt32 HeadingY, System.Data.SqlTypes.SqlInt32 HeadingZ)
		{
			const string thisID = "1886629764";
			System.Data.SqlClient.SqlCommand thisCommand;
			if(!this.isCommandCached(thisID))
			{
				// create and add to cache
				thisCommand = new System.Data.SqlClient.SqlCommand();

				thisCommand.Connection = _connection;
				thisCommand.CommandType = System.Data.CommandType.StoredProcedure;
				thisCommand.CommandText = "CreateTerrain";
					
				// Parameters:
					
				System.Data.SqlClient.SqlParameter param;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@AreaID";
				param.SourceColumn = "AreaID";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@ObjectTemplateName";
				param.SourceColumn = "ObjectTemplateName";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@ModelID";
				param.SourceColumn = "ModelID";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@PlayerID";
				param.SourceColumn = "PlayerID";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@EnumTerrainTypeID";
				param.SourceColumn = "EnumTerrainTypeID";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@X";
				param.SourceColumn = "X";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@Y";
				param.SourceColumn = "Y";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@Z";
				param.SourceColumn = "Z";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@HeadingX";
				param.SourceColumn = "HeadingX";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@HeadingY";
				param.SourceColumn = "HeadingY";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@HeadingZ";
				param.SourceColumn = "HeadingZ";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		

				// not sure of the usefullness of this
				// i never really got prepared statements
				thisCommand.Prepare();					
					
				_commands.Add(thisID, thisCommand);
			}
			else
			{
				thisCommand = (System.Data.SqlClient.SqlCommand)this._commands[thisID];
			}
				
				
			thisCommand.Parameters["@AreaID"].Value = AreaID;
		
			thisCommand.Parameters["@ObjectTemplateName"].Value = ObjectTemplateName;
		
			thisCommand.Parameters["@ModelID"].Value = ModelID;
		
			thisCommand.Parameters["@PlayerID"].Value = PlayerID;
		
			thisCommand.Parameters["@EnumTerrainTypeID"].Value = EnumTerrainTypeID;
		
			thisCommand.Parameters["@X"].Value = X;
		
			thisCommand.Parameters["@Y"].Value = Y;
		
			thisCommand.Parameters["@Z"].Value = Z;
		
			thisCommand.Parameters["@HeadingX"].Value = HeadingX;
		
			thisCommand.Parameters["@HeadingY"].Value = HeadingY;
		
			thisCommand.Parameters["@HeadingZ"].Value = HeadingZ;
		
								
			return thisCommand;
			
		}
	
			
		public System.Data.SqlClient.SqlCommand CreateTerrain()
		{
			const string thisID = "1886629764";
			System.Data.SqlClient.SqlCommand thisCommand;
			if(!this.isCommandCached(thisID))
			{
				// create and add to cache
				thisCommand = new System.Data.SqlClient.SqlCommand();

				thisCommand.Connection = _connection;
				thisCommand.CommandType = System.Data.CommandType.StoredProcedure;
				thisCommand.CommandText = "CreateTerrain";
					
				// Parameters:
					
				System.Data.SqlClient.SqlParameter param;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@AreaID";
				param.SourceColumn = "AreaID";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@ObjectTemplateName";
				param.SourceColumn = "ObjectTemplateName";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@ModelID";
				param.SourceColumn = "ModelID";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@PlayerID";
				param.SourceColumn = "PlayerID";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@EnumTerrainTypeID";
				param.SourceColumn = "EnumTerrainTypeID";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@X";
				param.SourceColumn = "X";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@Y";
				param.SourceColumn = "Y";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@Z";
				param.SourceColumn = "Z";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@HeadingX";
				param.SourceColumn = "HeadingX";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@HeadingY";
				param.SourceColumn = "HeadingY";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@HeadingZ";
				param.SourceColumn = "HeadingZ";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
							
					
				// not sure of the usefullness of this
				// i never really got prepared statements
				thisCommand.Prepare();					
					
				_commands.Add(thisID, thisCommand);
			}
			else
			{
				thisCommand = (System.Data.SqlClient.SqlCommand)this._commands[thisID];
			}

			return thisCommand;
			
		}
	
			
		public System.Data.SqlClient.SqlCommand EnumTerrainInSquare(System.Data.SqlTypes.SqlInt32 SmallestCoordX, System.Data.SqlTypes.SqlInt32 SmallestCoordZ, System.Data.SqlTypes.SqlInt32 LargestCoordX, System.Data.SqlTypes.SqlInt32 LargestCoordZ)
		{
			const string thisID = "2014630220";
			System.Data.SqlClient.SqlCommand thisCommand;
			if(!this.isCommandCached(thisID))
			{
				// create and add to cache
				thisCommand = new System.Data.SqlClient.SqlCommand();

				thisCommand.Connection = _connection;
				thisCommand.CommandType = System.Data.CommandType.StoredProcedure;
				thisCommand.CommandText = "EnumTerrainInSquare";
					
				// Parameters:
					
				System.Data.SqlClient.SqlParameter param;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@SmallestCoordX";
				param.SourceColumn = "SmallestCoordX";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@SmallestCoordZ";
				param.SourceColumn = "SmallestCoordZ";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@LargestCoordX";
				param.SourceColumn = "LargestCoordX";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@LargestCoordZ";
				param.SourceColumn = "LargestCoordZ";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		

				// not sure of the usefullness of this
				// i never really got prepared statements
				thisCommand.Prepare();					
					
				_commands.Add(thisID, thisCommand);
			}
			else
			{
				thisCommand = (System.Data.SqlClient.SqlCommand)this._commands[thisID];
			}
				
				
			thisCommand.Parameters["@SmallestCoordX"].Value = SmallestCoordX;
		
			thisCommand.Parameters["@SmallestCoordZ"].Value = SmallestCoordZ;
		
			thisCommand.Parameters["@LargestCoordX"].Value = LargestCoordX;
		
			thisCommand.Parameters["@LargestCoordZ"].Value = LargestCoordZ;
		
								
			return thisCommand;
			
		}
	
			
		public System.Data.SqlClient.SqlCommand EnumTerrainInSquare()
		{
			const string thisID = "2014630220";
			System.Data.SqlClient.SqlCommand thisCommand;
			if(!this.isCommandCached(thisID))
			{
				// create and add to cache
				thisCommand = new System.Data.SqlClient.SqlCommand();

				thisCommand.Connection = _connection;
				thisCommand.CommandType = System.Data.CommandType.StoredProcedure;
				thisCommand.CommandText = "EnumTerrainInSquare";
					
				// Parameters:
					
				System.Data.SqlClient.SqlParameter param;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@SmallestCoordX";
				param.SourceColumn = "SmallestCoordX";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@SmallestCoordZ";
				param.SourceColumn = "SmallestCoordZ";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@LargestCoordX";
				param.SourceColumn = "LargestCoordX";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@LargestCoordZ";
				param.SourceColumn = "LargestCoordZ";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
							
					
				// not sure of the usefullness of this
				// i never really got prepared statements
				thisCommand.Prepare();					
					
				_commands.Add(thisID, thisCommand);
			}
			else
			{
				thisCommand = (System.Data.SqlClient.SqlCommand)this._commands[thisID];
			}

			return thisCommand;
			
		}
	
			
		public System.Data.SqlClient.SqlCommand GetAreas(System.Data.SqlTypes.SqlInt32 MetaSize)
		{
			const string thisID = "1918629878";
			System.Data.SqlClient.SqlCommand thisCommand;
			if(!this.isCommandCached(thisID))
			{
				// create and add to cache
				thisCommand = new System.Data.SqlClient.SqlCommand();

				thisCommand.Connection = _connection;
				thisCommand.CommandType = System.Data.CommandType.StoredProcedure;
				thisCommand.CommandText = "GetAreas";
					
				// Parameters:
					
				System.Data.SqlClient.SqlParameter param;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@MetaSize";
				param.SourceColumn = "MetaSize";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		

				// not sure of the usefullness of this
				// i never really got prepared statements
				thisCommand.Prepare();					
					
				_commands.Add(thisID, thisCommand);
			}
			else
			{
				thisCommand = (System.Data.SqlClient.SqlCommand)this._commands[thisID];
			}
				
				
			thisCommand.Parameters["@MetaSize"].Value = MetaSize;
		
								
			return thisCommand;
			
		}
	
			
		public System.Data.SqlClient.SqlCommand GetAreas()
		{
			const string thisID = "1918629878";
			System.Data.SqlClient.SqlCommand thisCommand;
			if(!this.isCommandCached(thisID))
			{
				// create and add to cache
				thisCommand = new System.Data.SqlClient.SqlCommand();

				thisCommand.Connection = _connection;
				thisCommand.CommandType = System.Data.CommandType.StoredProcedure;
				thisCommand.CommandText = "GetAreas";
					
				// Parameters:
					
				System.Data.SqlClient.SqlParameter param;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@MetaSize";
				param.SourceColumn = "MetaSize";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
							
					
				// not sure of the usefullness of this
				// i never really got prepared statements
				thisCommand.Prepare();					
					
				_commands.Add(thisID, thisCommand);
			}
			else
			{
				thisCommand = (System.Data.SqlClient.SqlCommand)this._commands[thisID];
			}

			return thisCommand;
			
		}
	
			
		public System.Data.SqlClient.SqlCommand GetTerrain(System.Data.SqlTypes.SqlInt32 TerrainInstanceID)
		{
			const string thisID = "2078630448";
			System.Data.SqlClient.SqlCommand thisCommand;
			if(!this.isCommandCached(thisID))
			{
				// create and add to cache
				thisCommand = new System.Data.SqlClient.SqlCommand();

				thisCommand.Connection = _connection;
				thisCommand.CommandType = System.Data.CommandType.StoredProcedure;
				thisCommand.CommandText = "GetTerrain";
					
				// Parameters:
					
				System.Data.SqlClient.SqlParameter param;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@TerrainInstanceID";
				param.SourceColumn = "TerrainInstanceID";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		

				// not sure of the usefullness of this
				// i never really got prepared statements
				thisCommand.Prepare();					
					
				_commands.Add(thisID, thisCommand);
			}
			else
			{
				thisCommand = (System.Data.SqlClient.SqlCommand)this._commands[thisID];
			}
				
				
			thisCommand.Parameters["@TerrainInstanceID"].Value = TerrainInstanceID;
		
								
			return thisCommand;
			
		}
	
			
		public System.Data.SqlClient.SqlCommand GetTerrain()
		{
			const string thisID = "2078630448";
			System.Data.SqlClient.SqlCommand thisCommand;
			if(!this.isCommandCached(thisID))
			{
				// create and add to cache
				thisCommand = new System.Data.SqlClient.SqlCommand();

				thisCommand.Connection = _connection;
				thisCommand.CommandType = System.Data.CommandType.StoredProcedure;
				thisCommand.CommandText = "GetTerrain";
					
				// Parameters:
					
				System.Data.SqlClient.SqlParameter param;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@TerrainInstanceID";
				param.SourceColumn = "TerrainInstanceID";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
							
					
				// not sure of the usefullness of this
				// i never really got prepared statements
				thisCommand.Prepare();					
					
				_commands.Add(thisID, thisCommand);
			}
			else
			{
				thisCommand = (System.Data.SqlClient.SqlCommand)this._commands[thisID];
			}

			return thisCommand;
			
		}
	
			
		public System.Data.SqlClient.SqlCommand LogonPlayer(System.Data.SqlTypes.SqlString Email, System.Data.SqlTypes.SqlString Password)
		{
			const string thisID = "1838629593";
			System.Data.SqlClient.SqlCommand thisCommand;
			if(!this.isCommandCached(thisID))
			{
				// create and add to cache
				thisCommand = new System.Data.SqlClient.SqlCommand();

				thisCommand.Connection = _connection;
				thisCommand.CommandType = System.Data.CommandType.StoredProcedure;
				thisCommand.CommandText = "LogonPlayer";
					
				// Parameters:
					
				System.Data.SqlClient.SqlParameter param;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@Email";
				param.SourceColumn = "Email";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@Password";
				param.SourceColumn = "Password";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		

				// not sure of the usefullness of this
				// i never really got prepared statements
				thisCommand.Prepare();					
					
				_commands.Add(thisID, thisCommand);
			}
			else
			{
				thisCommand = (System.Data.SqlClient.SqlCommand)this._commands[thisID];
			}
				
				
			thisCommand.Parameters["@Email"].Value = Email;
		
			thisCommand.Parameters["@Password"].Value = Password;
		
								
			return thisCommand;
			
		}
	
			
		public System.Data.SqlClient.SqlCommand LogonPlayer()
		{
			const string thisID = "1838629593";
			System.Data.SqlClient.SqlCommand thisCommand;
			if(!this.isCommandCached(thisID))
			{
				// create and add to cache
				thisCommand = new System.Data.SqlClient.SqlCommand();

				thisCommand.Connection = _connection;
				thisCommand.CommandType = System.Data.CommandType.StoredProcedure;
				thisCommand.CommandText = "LogonPlayer";
					
				// Parameters:
					
				System.Data.SqlClient.SqlParameter param;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@Email";
				param.SourceColumn = "Email";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@Password";
				param.SourceColumn = "Password";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
							
					
				// not sure of the usefullness of this
				// i never really got prepared statements
				thisCommand.Prepare();					
					
				_commands.Add(thisID, thisCommand);
			}
			else
			{
				thisCommand = (System.Data.SqlClient.SqlCommand)this._commands[thisID];
			}

			return thisCommand;
			
		}
	
			
		public System.Data.SqlClient.SqlCommand SelectPlayer(System.Data.SqlTypes.SqlInt32 PlayerID)
		{
			const string thisID = "1806629479";
			System.Data.SqlClient.SqlCommand thisCommand;
			if(!this.isCommandCached(thisID))
			{
				// create and add to cache
				thisCommand = new System.Data.SqlClient.SqlCommand();

				thisCommand.Connection = _connection;
				thisCommand.CommandType = System.Data.CommandType.StoredProcedure;
				thisCommand.CommandText = "SelectPlayer";
					
				// Parameters:
					
				System.Data.SqlClient.SqlParameter param;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@PlayerID";
				param.SourceColumn = "PlayerID";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		

				// not sure of the usefullness of this
				// i never really got prepared statements
				thisCommand.Prepare();					
					
				_commands.Add(thisID, thisCommand);
			}
			else
			{
				thisCommand = (System.Data.SqlClient.SqlCommand)this._commands[thisID];
			}
				
				
			thisCommand.Parameters["@PlayerID"].Value = PlayerID;
		
								
			return thisCommand;
			
		}
	
			
		public System.Data.SqlClient.SqlCommand SelectPlayer()
		{
			const string thisID = "1806629479";
			System.Data.SqlClient.SqlCommand thisCommand;
			if(!this.isCommandCached(thisID))
			{
				// create and add to cache
				thisCommand = new System.Data.SqlClient.SqlCommand();

				thisCommand.Connection = _connection;
				thisCommand.CommandType = System.Data.CommandType.StoredProcedure;
				thisCommand.CommandText = "SelectPlayer";
					
				// Parameters:
					
				System.Data.SqlClient.SqlParameter param;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@PlayerID";
				param.SourceColumn = "PlayerID";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
							
					
				// not sure of the usefullness of this
				// i never really got prepared statements
				thisCommand.Prepare();					
					
				_commands.Add(thisID, thisCommand);
			}
			else
			{
				thisCommand = (System.Data.SqlClient.SqlCommand)this._commands[thisID];
			}

			return thisCommand;
			
		}
	
			
		public System.Data.SqlClient.SqlCommand SelectPlayerByPlayerKey(System.Data.SqlTypes.SqlGuid PlayerKey)
		{
			const string thisID = "1822629536";
			System.Data.SqlClient.SqlCommand thisCommand;
			if(!this.isCommandCached(thisID))
			{
				// create and add to cache
				thisCommand = new System.Data.SqlClient.SqlCommand();

				thisCommand.Connection = _connection;
				thisCommand.CommandType = System.Data.CommandType.StoredProcedure;
				thisCommand.CommandText = "SelectPlayerByPlayerKey";
					
				// Parameters:
					
				System.Data.SqlClient.SqlParameter param;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@PlayerKey";
				param.SourceColumn = "PlayerKey";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		

				// not sure of the usefullness of this
				// i never really got prepared statements
				thisCommand.Prepare();					
					
				_commands.Add(thisID, thisCommand);
			}
			else
			{
				thisCommand = (System.Data.SqlClient.SqlCommand)this._commands[thisID];
			}
				
				
			thisCommand.Parameters["@PlayerKey"].Value = PlayerKey;
		
								
			return thisCommand;
			
		}
	
			
		public System.Data.SqlClient.SqlCommand SelectPlayerByPlayerKey()
		{
			const string thisID = "1822629536";
			System.Data.SqlClient.SqlCommand thisCommand;
			if(!this.isCommandCached(thisID))
			{
				// create and add to cache
				thisCommand = new System.Data.SqlClient.SqlCommand();

				thisCommand.Connection = _connection;
				thisCommand.CommandType = System.Data.CommandType.StoredProcedure;
				thisCommand.CommandText = "SelectPlayerByPlayerKey";
					
				// Parameters:
					
				System.Data.SqlClient.SqlParameter param;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@PlayerKey";
				param.SourceColumn = "PlayerKey";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
							
					
				// not sure of the usefullness of this
				// i never really got prepared statements
				thisCommand.Prepare();					
					
				_commands.Add(thisID, thisCommand);
			}
			else
			{
				thisCommand = (System.Data.SqlClient.SqlCommand)this._commands[thisID];
			}

			return thisCommand;
			
		}
	
			
		public System.Data.SqlClient.SqlCommand TerrainSquareDetails(System.Data.SqlTypes.SqlInt32 AbstractionSize, System.Data.SqlTypes.SqlInt32 Offset)
		{
			const string thisID = "1998630163";
			System.Data.SqlClient.SqlCommand thisCommand;
			if(!this.isCommandCached(thisID))
			{
				// create and add to cache
				thisCommand = new System.Data.SqlClient.SqlCommand();

				thisCommand.Connection = _connection;
				thisCommand.CommandType = System.Data.CommandType.StoredProcedure;
				thisCommand.CommandText = "TerrainSquareDetails";
					
				// Parameters:
					
				System.Data.SqlClient.SqlParameter param;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@AbstractionSize";
				param.SourceColumn = "AbstractionSize";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@Offset";
				param.SourceColumn = "Offset";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		

				// not sure of the usefullness of this
				// i never really got prepared statements
				thisCommand.Prepare();					
					
				_commands.Add(thisID, thisCommand);
			}
			else
			{
				thisCommand = (System.Data.SqlClient.SqlCommand)this._commands[thisID];
			}
				
				
			thisCommand.Parameters["@AbstractionSize"].Value = AbstractionSize;
		
			thisCommand.Parameters["@Offset"].Value = Offset;
		
								
			return thisCommand;
			
		}
	
			
		public System.Data.SqlClient.SqlCommand TerrainSquareDetails()
		{
			const string thisID = "1998630163";
			System.Data.SqlClient.SqlCommand thisCommand;
			if(!this.isCommandCached(thisID))
			{
				// create and add to cache
				thisCommand = new System.Data.SqlClient.SqlCommand();

				thisCommand.Connection = _connection;
				thisCommand.CommandType = System.Data.CommandType.StoredProcedure;
				thisCommand.CommandText = "TerrainSquareDetails";
					
				// Parameters:
					
				System.Data.SqlClient.SqlParameter param;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@AbstractionSize";
				param.SourceColumn = "AbstractionSize";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@Offset";
				param.SourceColumn = "Offset";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
							
					
				// not sure of the usefullness of this
				// i never really got prepared statements
				thisCommand.Prepare();					
					
				_commands.Add(thisID, thisCommand);
			}
			else
			{
				thisCommand = (System.Data.SqlClient.SqlCommand)this._commands[thisID];
			}

			return thisCommand;
			
		}
	
			
		public System.Data.SqlClient.SqlCommand UpdateTerrain(System.Data.SqlTypes.SqlInt32 TerrainInstanceID, System.Data.SqlTypes.SqlInt32 AreaID, System.Data.SqlTypes.SqlString ObjectTemplateName, System.Data.SqlTypes.SqlInt32 ModelID, System.Data.SqlTypes.SqlInt32 PlayerID, System.Data.SqlTypes.SqlInt32 EnumTerrainTypeID, System.Data.SqlTypes.SqlInt32 X, System.Data.SqlTypes.SqlInt32 Y, System.Data.SqlTypes.SqlInt32 Z, System.Data.SqlTypes.SqlInt32 HeadingX, System.Data.SqlTypes.SqlInt32 HeadingY, System.Data.SqlTypes.SqlInt32 HeadingZ)
		{
			const string thisID = "2094630505";
			System.Data.SqlClient.SqlCommand thisCommand;
			if(!this.isCommandCached(thisID))
			{
				// create and add to cache
				thisCommand = new System.Data.SqlClient.SqlCommand();

				thisCommand.Connection = _connection;
				thisCommand.CommandType = System.Data.CommandType.StoredProcedure;
				thisCommand.CommandText = "UpdateTerrain";
					
				// Parameters:
					
				System.Data.SqlClient.SqlParameter param;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@TerrainInstanceID";
				param.SourceColumn = "TerrainInstanceID";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@AreaID";
				param.SourceColumn = "AreaID";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@ObjectTemplateName";
				param.SourceColumn = "ObjectTemplateName";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@ModelID";
				param.SourceColumn = "ModelID";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@PlayerID";
				param.SourceColumn = "PlayerID";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@EnumTerrainTypeID";
				param.SourceColumn = "EnumTerrainTypeID";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@X";
				param.SourceColumn = "X";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@Y";
				param.SourceColumn = "Y";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@Z";
				param.SourceColumn = "Z";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@HeadingX";
				param.SourceColumn = "HeadingX";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@HeadingY";
				param.SourceColumn = "HeadingY";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@HeadingZ";
				param.SourceColumn = "HeadingZ";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		

				// not sure of the usefullness of this
				// i never really got prepared statements
				thisCommand.Prepare();					
					
				_commands.Add(thisID, thisCommand);
			}
			else
			{
				thisCommand = (System.Data.SqlClient.SqlCommand)this._commands[thisID];
			}
				
				
			thisCommand.Parameters["@TerrainInstanceID"].Value = TerrainInstanceID;
		
			thisCommand.Parameters["@AreaID"].Value = AreaID;
		
			thisCommand.Parameters["@ObjectTemplateName"].Value = ObjectTemplateName;
		
			thisCommand.Parameters["@ModelID"].Value = ModelID;
		
			thisCommand.Parameters["@PlayerID"].Value = PlayerID;
		
			thisCommand.Parameters["@EnumTerrainTypeID"].Value = EnumTerrainTypeID;
		
			thisCommand.Parameters["@X"].Value = X;
		
			thisCommand.Parameters["@Y"].Value = Y;
		
			thisCommand.Parameters["@Z"].Value = Z;
		
			thisCommand.Parameters["@HeadingX"].Value = HeadingX;
		
			thisCommand.Parameters["@HeadingY"].Value = HeadingY;
		
			thisCommand.Parameters["@HeadingZ"].Value = HeadingZ;
		
								
			return thisCommand;
			
		}
	
			
		public System.Data.SqlClient.SqlCommand UpdateTerrain()
		{
			const string thisID = "2094630505";
			System.Data.SqlClient.SqlCommand thisCommand;
			if(!this.isCommandCached(thisID))
			{
				// create and add to cache
				thisCommand = new System.Data.SqlClient.SqlCommand();

				thisCommand.Connection = _connection;
				thisCommand.CommandType = System.Data.CommandType.StoredProcedure;
				thisCommand.CommandText = "UpdateTerrain";
					
				// Parameters:
					
				System.Data.SqlClient.SqlParameter param;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@TerrainInstanceID";
				param.SourceColumn = "TerrainInstanceID";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@AreaID";
				param.SourceColumn = "AreaID";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@ObjectTemplateName";
				param.SourceColumn = "ObjectTemplateName";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@ModelID";
				param.SourceColumn = "ModelID";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@PlayerID";
				param.SourceColumn = "PlayerID";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@EnumTerrainTypeID";
				param.SourceColumn = "EnumTerrainTypeID";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@X";
				param.SourceColumn = "X";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@Y";
				param.SourceColumn = "Y";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@Z";
				param.SourceColumn = "Z";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@HeadingX";
				param.SourceColumn = "HeadingX";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@HeadingY";
				param.SourceColumn = "HeadingY";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
		
				param = new System.Data.SqlClient.SqlParameter();		
				param.ParameterName = "@HeadingZ";
				param.SourceColumn = "HeadingZ";
				param.SourceVersion = System.Data.DataRowVersion.Current;
				thisCommand.Parameters.Add(param);			
				param = null;
							
					
				// not sure of the usefullness of this
				// i never really got prepared statements
				thisCommand.Prepare();					
					
				_commands.Add(thisID, thisCommand);
			}
			else
			{
				thisCommand = (System.Data.SqlClient.SqlCommand)this._commands[thisID];
			}

			return thisCommand;
			
		}
	
	

		

	

	}
	
}
