using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using UpdateControls;

using Strive.Client.Model;


namespace Strive.Client.NavigationModel
{
    public class WorldNavigation
    {
        private HashSet<EntityModel> _selectedEntities = new HashSet<EntityModel>();

        #region Independent properties
        // Generated by Update Controls --------------------------------
        private Independent _indSelectedEntities = new Independent();

        public void SetSelectedEntity(EntityModel selectedEntity)
        {
            _indSelectedEntities.OnSet();
            _selectedEntities.Clear();
            _selectedEntities.Add(selectedEntity);
        }

        public void AddSelectedEntity(EntityModel selectedEntity)
        {
            _indSelectedEntities.OnSet();
            _selectedEntities.Add(selectedEntity);
        }

        public void RemoveSelectedEntity(EntityModel selectedEntity)
        {
            _indSelectedEntities.OnSet();
            _selectedEntities.Remove(selectedEntity);
        }

        public IEnumerable<EntityModel> SelectedEntities
        {
            get { _indSelectedEntities.OnGet(); return _selectedEntities; }
        }
        // End generated code --------------------------------
        #endregion
    }
}
